//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class aspnet_Users
{
    public aspnet_Users()
    {
        this.Recipes = new HashSet<Recipe>();
    }

    public System.Guid ApplicationId { get; set; }
    public System.Guid UserId { get; set; }
    public string UserName { get; set; }
    public string LoweredUserName { get; set; }
    public string MobileAlias { get; set; }
    public bool IsAnonymous { get; set; }
    public System.DateTime LastActivityDate { get; set; }

    public virtual ICollection<Recipe> Recipes { get; set; }
}

public partial class FoodList
{
    public int NDB_Number { get; set; }
    public int RecipeID { get; set; }
    public string SelectedUnit { get; set; }
    public decimal Measure { get; set; }

    public virtual Ingredient Ingredient { get; set; }
    public virtual Recipe Recipe { get; set; }
}

public partial class Ingredient
{
    public Ingredient()
    {
        this.FoodLists = new HashSet<FoodList>();
    }

    public int NDB_Number { get; set; }
    public string Description { get; set; }
    public Nullable<decimal> Water { get; set; }
    public Nullable<decimal> Calories__kcal_ { get; set; }
    public Nullable<decimal> Protein { get; set; }
    public Nullable<decimal> Total_fat { get; set; }
    public Nullable<decimal> Ash { get; set; }
    public Nullable<decimal> Carbohydrate { get; set; }
    public Nullable<decimal> Fiber { get; set; }
    public Nullable<decimal> Sugars { get; set; }
    public Nullable<decimal> Calcium { get; set; }
    public Nullable<decimal> Iron { get; set; }
    public Nullable<decimal> Magnesium { get; set; }
    public Nullable<decimal> Phosphorus { get; set; }
    public Nullable<decimal> Potassium { get; set; }
    public Nullable<decimal> Sodium { get; set; }
    public Nullable<decimal> Zinc { get; set; }
    public Nullable<decimal> Copper { get; set; }
    public Nullable<decimal> Manganese { get; set; }
    public Nullable<decimal> Selenium { get; set; }
    public Nullable<decimal> Vitamin_C { get; set; }
    public Nullable<decimal> Thiamin { get; set; }
    public Nullable<decimal> Riboflavin { get; set; }
    public Nullable<decimal> Niacin { get; set; }
    public Nullable<decimal> Pantothenic_acid { get; set; }
    public Nullable<decimal> Vitamin_B6 { get; set; }
    public Nullable<decimal> Total_folate { get; set; }
    public Nullable<decimal> Folic_acid { get; set; }
    public Nullable<decimal> Food_folate { get; set; }
    public Nullable<decimal> Folate__ug_ { get; set; }
    public Nullable<decimal> Choline { get; set; }
    public Nullable<decimal> Vitamin_B12 { get; set; }
    public Nullable<decimal> Vitamin_A__IU_ { get; set; }
    public Nullable<decimal> Vitamin_A__ug_ { get; set; }
    public Nullable<decimal> Retinol { get; set; }
    public Nullable<decimal> Alpha_carotene { get; set; }
    public Nullable<decimal> Beta_carotene { get; set; }
    public Nullable<decimal> Beta_cryptoxanthin { get; set; }
    public Nullable<decimal> Lycopene { get; set; }
    public Nullable<decimal> Lutein_zeazanthin { get; set; }
    public Nullable<decimal> Vitamin_E { get; set; }
    public Nullable<decimal> Vitamin_D__ug_ { get; set; }
    public Nullable<decimal> Vitamin_D__IU_ { get; set; }
    public Nullable<decimal> Vitamin_K { get; set; }
    public Nullable<decimal> Saturated_fat { get; set; }
    public Nullable<decimal> Mono_fat { get; set; }
    public Nullable<decimal> Poly_fat { get; set; }
    public Nullable<decimal> Cholesterol { get; set; }
    public Nullable<decimal> Weight1 { get; set; }
    public string Weight1_Description { get; set; }
    public Nullable<decimal> Weight2 { get; set; }
    public string Weight2_Description { get; set; }
    public Nullable<decimal> Percent_refuse { get; set; }

    public virtual ICollection<FoodList> FoodLists { get; set; }
}

public partial class Recipe
{
    public Recipe()
    {
        this.FoodLists = new HashSet<FoodList>();
    }

    public int RecipeID { get; set; }
    public System.Guid UserID { get; set; }
    public string Name { get; set; }
    public int Servings { get; set; }
    public string Instructions { get; set; }

    public virtual aspnet_Users aspnet_Users { get; set; }
    public virtual ICollection<FoodList> FoodLists { get; set; }
}
